### ISSUE TITLE
Could you please tell me why the inner product argument needs Protocol 1?

### ISSUE THREAD

**Issue by p1gd0g** [AdamISZ/from0k2bp#4]
I just don't make sense of why c=<a,b> can be ensured by raising u to the power x.
Thank your for any advise.

**Comment by AdamISZ** [comment]
It's not that c = <a,b> is ensured by raising u to the power x.

Ensuring that, given a commitment to vectors a, b and a commitment to c, that c is in fact the value <a, b> is addressed by using a compact proof of the type laid out I Section 4, 5 and 6.1 of this document.

But the reason that u is raised to the power x, where x is a challenge from the verifier, is to convert that compact proof into a zero knowledge argument of knowledge.

The problem is that the inner product proof of Bootle (section 5 in the doc) and bulletproofs (section 6.1) are not zero-knowledge in themselves. In the last step of the recursion, you actually reveal the values.
Protocol 1, as an overlay, using the challenge x to "blind", converts the argument into a zero knowledge argument.

**Comment by apoelstra** [comment]
Protocol 2 proves the following statement: "given a point P, there exist vectors **a** and **b** such that P = **aG** + **bH** + *<*a*, *b*>G". This problem is that this statement isn't very useful. If I give you a point *P*, it's nice to know that I can deconstruct it into some sort of inner product thing, but in practice you typically know what <*a*, *b*> should be, and you want a proof that it's the correct thing. We'll call the statement being proved here Statement 1.

So the statement we really want is "Given P and *c*, there exist vectors **a** and **b** such that P = **aG** + **bH** **and furthermore** *c* = <*a*, *b*>". Same as above, but I've moved the actual inner  product "out of hiding" by taking it out of P and making it explicit. Call this Statement 2.

The obvious way prove the Statement 2, which we want, given only a proof system for the Statement 2, which we have, would be for the verifier to compute "P' = P + *c*G" and ask for a proof of Statement 1 on P'. This doesn't work, because a malicious prover could simply prove Statement 1 on a point P', then choose *c* to be whatever he wanted and provide *c*, P = P' - *c*G to a verifier.

There are a few ways to prevent this. The tactic chosen in the paper is to force the prover to choose P before he learns what G is. Then he can't set P = P' - *c*G; for a given P' this is either true or it isn't! Instead, the prover is forced to choose P' = P + *c*G, which is exactly what we want him to.

So how can we force the prover to choose P before knowing G? Easy, hash P to get a new value *x* and replace G with *x*G.

**Comment by AdamISZ** [comment]
Cheers Andrew. I was always confused about this distinction, but it's my own fault; the Bulletproofs paper does actually state it fairly clearly (see (2) and (3) and compare), but I wasn't careful enough in reading, so had the wrong idea ('hiding'). Although your explanation very helpfully makes it all explicit (the causality forcing).

> The obvious way prove the Statement 2, which we want, given only a proof system for the Statement 2

I think you meant Statement 1 at the end, there

**Comment by apoelstra** [comment]
Yep, thanks, fixed typo

**Comment by AdamISZ** [comment]
Was going to add a bit more text on this in the 0f719da8b3674d77137fc2393f5d84d580f8d1c9 fixup I just did, but realised on re-reading that I had more or less correctly understood this at the time of writing; see both the first and the last paragraph of 6.1.2. Would be possible to add more detail but not sure it's worth it.

@p1gd0g If you need more help than Andrew's explanation above, let me know, otherwise I'll close.

**Comment by p1gd0g** [comment]
Thank your guys, finally I understand it!
